"""S2 — the four-lens audit, driven by the Claude Code session instead of an SDK call.

`run_audit` does not call a model. It renders one self-contained prompt file per lens
into `audit/prompts/<lens>.md` and stops. The driver (the interactive session) opens
one prompt at a time, performs that audit, and writes `audit/<lens>.json`.

Working one lens per turn preserves the property the SDK sessions gave for free:
four independent readings rather than one reading echoed four times. It is weaker
than process isolation — a single context can remember the previous lens — so the
prompt says so explicitly and the lenses are ordered to be run separately.

What is NOT weaker is provenance. `load_reports` re-checks every finding's
`evidence_quote` against the parsed paper and, when the finding cites a cell, against
that cell's real contents. The driver is a language model; the harness does not take
its word for anything it can verify itself.
"""
from __future__ import annotations

import os
import re

from .. import pdf, state
from ..artifacts import Finding, LensReport, PaperDoc
from ..config import Config
from ..prompts import audit as P

LENSES = tuple(P.LENSES)
SECTION_BUDGET_CHARS = int(os.environ.get("SH_AUDIT_BUDGET_CHARS", "70000"))
_SEVERITIES = ("FATAL", "MAJOR", "MINOR")
_CELL_REF = re.compile(r"T(\d+):r(\d+):c(\d+)")
_QUOTE_MIN = 8
_WS = re.compile(r"\s+")


def _flat(s: str) -> str:
    return _WS.sub("", (s or "").lower())


def render_numbers(doc: PaperDoc) -> str:
    out = []
    for n in doc.reported_numbers:
        where = n.table_ref or f"p{n.page}"
        if n.table_ref:
            out.append(f"- [{where}] {n.method} · {n.metric} = {n.value}"
                       f"{f' (±{n.seeds_or_variance})' if n.seeds_or_variance else ' (NO VARIANCE REPORTED)'}"
                       f"  << {n.benchmark}")
        else:
            out.append(f"- [{where}] prose claim: \"{n.source_quote}\"")
    return "\n".join(out)


def context(doc: PaperDoc) -> dict[str, str]:
    return {
        "sections_text": pdf.render_sections(doc.sections, SECTION_BUDGET_CHARS),
        "tables_text": pdf.render_tables(doc.tables),
        "claims_text": "(none pre-extracted — identify the paper's claims yourself "
                       "from the sections below; that judgement is part of your job)",
        "numbers_text": render_numbers(doc),
    }


def _header(lens: str, pid: str) -> str:
    return f"""<!-- generated by `run.py node audit_paper --paper {pid}` — do not edit -->

# Audit lens: `{lens}`  ·  paper `{pid}`

**Driver instructions.** Perform this audit now, then write your result to
`projects/{pid}/audit/{lens}.json` as a single JSON object matching the schema at the
end of this file. Run each lens in a SEPARATE turn and do not let one lens's findings
influence another — they are meant to be independent readings.

Every finding is re-verified when the report is built: a finding whose
`evidence_quote` is not actually present in this paper, or whose cited cell does not
contain what it says, is DROPPED. Quote exactly.

---

"""


def run_audit(cfg: Config, pid: str, lenses: tuple[str, ...] = LENSES) -> dict:
    """Write one prompt file per lens. Does not call a model."""
    root = state.project_dir(cfg, pid)
    doc_path = root / "paper" / "doc.json"
    if not doc_path.exists():
        return {"error": f"no ingested paper for '{pid}' — run ingest_paper first"}
    doc = PaperDoc(**state.read_json(doc_path))
    state.set_phase(cfg, pid, "audit")

    ctx = context(doc)
    pdir = root / "audit" / "prompts"
    pdir.mkdir(parents=True, exist_ok=True)
    for lens in lenses:
        body = _header(lens, pid) + P.build(lens, doc.title, **ctx)
        (pdir / f"{lens}.md").write_text(body, encoding="utf-8")

    done = [ln for ln in lenses if (root / "audit" / f"{ln}.json").exists()]
    todo = [ln for ln in lenses if ln not in done]
    state.append_log(
        cfg, pid, artifact_type="audit_prompts", phase="audit",
        headers={"lenses": list(lenses), "awaiting": todo, "complete": done,
                 "chars": sum(len((pdir / f'{ln}.md').read_text(encoding='utf-8')) for ln in lenses)},
        path=str(pdir),
    )
    return {
        "paper_id": pid, "title": doc.title,
        "prompts": {ln: str(pdir / f"{ln}.md") for ln in lenses},
        "awaiting": todo, "complete": done,
        "next": (f"Read each prompt in audit/prompts/, perform that audit, and write "
                 f"audit/<lens>.json. Awaiting: {', '.join(todo) or 'none'}.")
        if todo else "All four lenses have results; run synthesize_report.",
    }


def load_reports(cfg: Config, pid: str, doc: PaperDoc) -> tuple[list[LensReport], int]:
    """Load every lens result, dropping findings that cannot be substantiated.

    Returns (reports, n_dropped). A lens whose file is missing or unparseable yields
    an EMPTY report rather than an exception — one bad lens must not sink the panel,
    and the report names which lenses actually ran, so an empty one can never be
    mistaken for a clean bill of health.
    """
    root = state.project_dir(cfg, pid)
    corpus = _flat("".join(s.text for s in doc.sections))
    by_idx = {t.table_idx: t for t in doc.tables}
    reports, dropped = [], 0
    for lens in LENSES:
        path = root / "audit" / f"{lens}.json"
        if not path.exists():
            continue
        try:
            raw = state.read_json(path)
        except Exception:
            reports.append(LensReport(lens=lens, notes="(unparseable lens file)"))
            continue
        report, n = _coerce(lens, raw, corpus, by_idx)
        reports.append(report)
        dropped += n
    return reports, dropped


def _substantiated(quote: str, ref: str, corpus: str, by_idx: dict) -> bool:
    """Is this quote really in the paper — and if it cites a cell, is it that cell?

    The length floor applies to PROSE quotes only. A short prose fragment matches
    anywhere and proves nothing, but a cell citation is already pinned to exact
    coordinates, so "0.0001" at T1:r0:c1 is the most checkable evidence there is —
    and rejecting it would throw away precisely the table numbers this harness exists
    to audit.
    """
    q = _flat(quote)
    if not q:
        return False
    m = _CELL_REF.fullmatch((ref or "").strip())
    if m:
        t = by_idx.get(int(m.group(1)))
        return t is not None and _flat(t.cell(int(m.group(2)), int(m.group(3)))) == q
    return len(q) >= _QUOTE_MIN and q in corpus


def _coerce(lens: str, data, corpus: str, by_idx: dict) -> tuple[LensReport, int]:
    if not isinstance(data, dict):
        return LensReport(lens=lens, notes="(lens file was not a JSON object)"), 0
    findings, dropped = [], 0
    for i, f in enumerate(data.get("findings") or []):
        if not isinstance(f, dict):
            dropped += 1
            continue
        statement = str(f.get("statement") or "").strip()
        quote = str(f.get("evidence_quote") or "").strip()
        ref = str(f.get("evidence_ref") or "").strip()
        if not statement or not _substantiated(quote, ref, corpus, by_idx):
            dropped += 1
            continue
        sev = str(f.get("severity") or "").upper()
        findings.append(Finding(
            finding_id=str(f.get("finding_id") or f"{lens}-{i + 1:02d}"),
            lens=lens, severity=sev if sev in _SEVERITIES else "MINOR",
            title=str(f.get("title") or statement)[:90], statement=statement,
            target=str(f.get("target") or ""), evidence_quote=quote, evidence_ref=ref,
            counter_explanations=[str(c) for c in (f.get("counter_explanations") or [])
                                 if isinstance(c, (str, int, float))],
            verifiable_by_experiment=bool(f.get("verifiable_by_experiment")),
        ))
    return LensReport(
        lens=lens, findings=findings,
        unasked_question=str(data.get("unasked_question") or "").strip(),
        notes=str(data.get("notes") or ""),
    ), dropped
